import {
  absoluteUrl,
  ARCHITECTURE_URL,
  GITHUB_URL,
  GETTING_STARTED_URL,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_STATUS,
} from '../_lib/site';
import { blogPostPath, indexableBlogPosts } from '../_lib/blog';

export function GET() {
  const body = [
    `# ${SITE_NAME}`,
    '',
    SITE_DESCRIPTION,
    '',
    'Textbutler is an AI butler for your messages, running on your Mac. Turn it on for the chats you choose in iMessage, WhatsApp, or Beeper, and it replies as a clearly marked assistant that keeps notes on each person in a folder you can open and edit. Automatic replies stay off until you connect an AI account, turn them on for a contact, and resume the butler. The AI provider you connect sees the context it needs to write a reply. Textbutler is free and MIT licensed.',
    '',
    'The website is informational. It never receives private message history, contacts, profiles, or drafts.',
    '## Current Textbutler development status',
    SITE_STATUS,
    'Textbutler is a macOS CLI, guided terminal, background daemon, and menu bar companion. It includes iMessage, WhatsApp, and Beeper setup through Ghostget, direct-conversation enrollment, optional recent-history import, editable memory for each contact, hooks, an inbox, and sending replies you write yourself. An agent-facing JSON CLI lists conversations, reads and summarizes history, writes drafts, and sends only messages you explicitly authorize, using the same staged actions the butler uses. Each contact’s context lives in ordinary files the butler maintains and revises. New installations start paused and new contacts start disabled.',
    'Run bun run textbutler tui from a checkout after installing pinned dependencies. The guided terminal covers setup, messaging connections, conversation selection, inbox review, and sending. Typed replies need a ready messaging connection but no AI account. The optional menu bar companion downloads a prebuilt runner, checked against a pinned hash, and needs no local Rust build.',
    'Default disclosure: 🤖{ hello this is my response }. The three symbols are configurable per contact and may be cleared. Clearing all three sends plain text. Full draft review uses replies show DRAFT; sending a generated draft requires replies send DRAFT DIGEST with the exact review digest. A menu preview cannot send a draft. A submitted result proves provider acceptance, not delivery.',
    'AI replies use a Claude Code or Codex subscription connected through xcb (https://github.com/hraness/xcb), and only from the local install that bun run textbutler:install builds. The installer refuses to build unless the source files it checks and both contact permission profiles match the last reviewed version. Running from source never writes AI replies. Signing in to an AI account or adding an API key does not by itself turn on suggestions or automatic replies; the account must pass providers check. Automatic replies also need the contact turned on and the butler resumed. An optional fast-reply mode, turned on in the host.json settings file, has a Qwen model through Vercel AI Gateway or a model server on your Mac write the replies instead; turning a contact on still needs an xcb account that passes providers check. The Claude API route is not available in any build of this repository; it needs its own separately reviewed runtime and is billed separately from a Claude Code subscription. Test inference and delivery on your own account before relying on them.',
    'Through xcb, the model gets no tools of its own, and xcb keeps the subscription sign-in. The model can ask Textbutler to read or edit one contact folder, fetch public web pages, or propose actions in that conversation; Textbutler checks each request and does the sending. Shell commands, other contact folders, credentials, and permission changes are out of reach. Hosted AI providers process the context they receive under their own data policies. Beeper supports text-only automation for its linked apps; iMessage and WhatsApp actions depend on the connection and its permissions. Some iMessage rich actions require a separately configured Messages bridge and disabled System Integrity Protection; Textbutler never changes that setting. App Clips, mini apps, and Linq integration are not supported. Textbutler is MIT licensed, and its source also serves as an example app for developers building on xcb.',
    `Guided setup: ${GETTING_STARTED_URL}`,
    `Messaging app support and live limitations: ${GITHUB_URL}/blob/main/docs/textbutler/messaging-apps.md`,
    `Subscription application contract: ${GITHUB_URL}/blob/main/docs/textbutler/native-subscription.md`,
    `Architecture: ${ARCHITECTURE_URL}`,
    '',
    '## Legacy Message Like Me history tools',
    'The following catalog describes the published Message Like Me history reader and its checked historical producer versions. It is not a Textbutler live transport support matrix. Installing the legacy package does not install Textbutler or enable automatic replies.',
    'Beeper via Ghostget lets users bring a finished private bundle into the same local evidence corpus as other sources. Ghostget v0.17.1 adapter beeper-local v2.4.0 owns 32 reviewed Beeper operations: 26 run through one pinned Beeper CLI 0.6.2 executable, including supported actions and writes, plus six fixed Desktop loopback reads. The executable’s reported 0.6.2 is runtime authority; the upstream tagged packages/cli/package.json declaration of 0.6.1 is provenance only. Message Like Me receives no provider credentials, never calls Ghostget or Beeper operations, and never sends; it does not claim complete history.',
    'Supported sources are Apple Messages; X data archive DMs, not X Chat; the finished Beeper bundle from Ghostget’s internal bounded v1 export; native WhatsApp via Ghostget and official Wacli through a one-account v2 bundle; and macOS Contacts for optional label enrichment. Every ingest path is read-only with respect to its source. Message Like Me does not invoke provider operations or access a network.',
    'The Ghostget v0.17.1 and Wacli v0.15.0 WhatsApp producer omits reaction-shaped rows with reaction-state-unproven because current active or removed state cannot be proved. An empty reaction artifact is unobservable reaction behavior, not evidence that no reactions occurred.',
    '',
    '## Optional development support',
    'Textbutler offers optional paid development support and no newsletter. `messagelikeme support` and `textbutler support` show the current options; agents follow `support protocol --json` for the closeout flow, and `HRANESS_SUPPORT_AUDIENCE=off` turns incidental notices off.',
    '',
    '## Canonical pages',
    `- ${absoluteUrl('/')}`,
    `- ${absoluteUrl('/sources')}`,
    `- ${absoluteUrl('/docs')}`,
    `- ${absoluteUrl('/methodology')}`,
    `- ${absoluteUrl('/research')}`,
    `- ${absoluteUrl('/about')}`,
    '',
    '## Blog',
    `- ${absoluteUrl('/blog')}`,
    ...indexableBlogPosts().map((post) => `- [${post.title}](${absoluteUrl(blogPostPath(post))}): ${post.dek}`),
    '',
    '## Source',
    `- ${GITHUB_URL}`,
    '',
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
