import { ProviderMarkChip } from '@hraness/design-kit/react/server';
import Link from 'next/link';
import { SiteFooter, SiteHeader } from '../_components/site-chrome';
import { absoluteUrl, ARCHITECTURE_URL, GITHUB_URL, pageMetadata, serializeJsonLd, SITE_DESCRIPTION, SITE_NAME, SITE_STATUS } from '../_lib/site';

export const metadata = pageMetadata({ title: 'About', description: 'Why Textbutler gives each relationship its own context, makes the assistant visible, and keeps control on your Mac.', path: '/about' });
const aboutJsonLd = { '@context': 'https://schema.org', '@type': 'AboutPage', name: `About ${SITE_NAME}`, url: absoluteUrl('/about'), description: SITE_DESCRIPTION, mainEntity: { '@id': `${absoluteUrl('/')}#application` }, isPartOf: { '@id': `${absoluteUrl('/')}#website` } };

export default function AboutPage() {
  return <><SiteHeader /><main className="document-page" id="main-content" tabIndex={-1}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(aboutJsonLd) }} />
    <header className="document-hero"><h1>Why Textbutler works the way it does</h1><p>Textbutler is an AI butler for the iMessage, WhatsApp, and Beeper chats you choose on your Mac. Turn it on for one person, and it replies as a clearly marked assistant that knows your history with them.</p><a href={GITHUB_URL}>View the open-source project</a></header>
    <section className="about-grid" aria-label="Product principles">
      <article><h2>Let your agent do the work</h2><p className="provider-marks"><ProviderMarkChip mark="claudecode" size={20} /><ProviderMarkChip mark="codex" size={20} /></p><p>Connect a Claude Code or Codex subscription through xcb, and the butler reads the conversations you choose, sums up what needs an answer, and drafts or sends replies within what each contact allows. An agent you run yourself can use the same JSON commands.</p></article>
      <article><h2>Give each relationship its own context</h2><p>A contact folder holds standing guidance the butler reads but can’t change, dated memories, preferences, and sources. It learns from conversation, and you can inspect and edit every file. Settings and permission grants live outside the agent’s editable context.</p></article>
      <article><h2>Keep the decision with you</h2><p>Text replies carry a disclosure by default, starting with {'🤖{ hello this is my response }'}. You can change or clear its three symbols, and you see the complete text of any reply before you send or approve it. Choose the contacts it may help, set the active limit, and pause it globally or per contact. Smart response is designed to yield while you are talking; keyword-only mode waits for a direct invitation.</p></article>
    </section>
    <section className="about-sources" aria-labelledby="about-build-title"><div><h2 id="about-build-title">What works today</h2></div><div><p>{SITE_STATUS}</p><p>Make the local build with <code>bun run textbutler:install</code>. It refuses to build if the source files it checks differ from the last reviewed version, and running from source never writes AI replies. The Claude API route isn’t available in any build of this repository. New installations start paused, and the optional menu bar companion downloads a prebuilt runner. Test replies and delivery on your own account before you rely on them.</p><a href={`${GITHUB_URL}/blob/main/docs/textbutler/getting-started.md`}>Open the guided setup instructions</a><p><a href="https://github.com/hraness/xcb">xcb</a> keeps your AI sign-in and gives the model no tools of its own. Textbutler decides who gets a reply and does the sending. Its MIT-licensed source also serves as an example app for developers building on xcb.</p><p><a href={ARCHITECTURE_URL}>Read the architecture</a></p></div></section>
    <section className="about-sources" aria-labelledby="about-history-title"><div><h2 id="about-history-title">What we are carrying forward</h2></div><div><p>Textbutler replaced Message Like Me, an earlier experiment in studying your own message history. Its history readers and methodology are still available as legacy tools, and they shaped how contact memory works. They only read old messages; they don’t connect Textbutler to live conversations.</p><Link href="/sources">Explore the legacy history tools</Link></div></section>
    <nav className="document-next" aria-label="Learn more"><Link href="/docs">Read the project docs</Link><Link href="/methodology">Legacy methodology</Link><Link href="/research">Legacy research</Link></nav>
  </main><SiteFooter path="/about" /></>;
}
